#! /usr/bin/env sh

# Just for the case it is not being called in a profile env
# I don't know if is even possible, but better safe than sorry
export PATH

for dir in "$HOME/.cargo/bin" "$HOME/go/bin" "$HOME/bin" "$HOME/.local/bin" "$HOME/.asdf/bin" "$HOME/.asdf/shims"; do
	if [ -d "$dir" ]; then
		PATH="$dir:$PATH"
	fi
done

DOTFILES_HOME="${DOTFILES_HOME:-$HOME/dotfiles}"
export DOTFILES_HOME

if [ -d "$DOTFILES_HOME" ]; then
	PATH="$DOTFILES_HOME/bin:$PATH"
	. "$DOTFILES_HOME/sh/variables"
	. "$DOTFILES_HOME/sh/aliases"
fi
