#! /usr/bin/env sh

# It's also a script in $DOTFILES_HOME/bin
# Duplicated for compatiblity in envs without the bin on the path
if ! type is_executable > /dev/null 2>&1; then
	is_executable() {
		type "$@" > /dev/null 2>&1
	}
fi

# It's also a script in $DOTFILES_HOME/bin
# Duplicated for compatiblity in envs without the bin on the path
if ! is_executable choose; then
	choose() (
		test_cmd="$1"
		shift

		for opt; do
			if eval " > /dev/null $test_cmd \"$opt\""; then
				echo "$opt"
				return
			fi
		done

		return 1
	)
fi

first_line() {
	line=
	IFS= read -r line
	printf "%s" "$line"
}

export SAVEHIST=300000

export DOTFILES_HOME="${DOTFILES_HOME:-$HOME/dotfiles}"

export DOWNLOADS_DIR="$(choose "test -d" "$HOME/Downloads" "$HOME/Transferências")"
export DOCUMENTS_DIR="$(choose "test -d" "$HOME/Documents" "$HOME/Documentos")"
export WORKSPACE_DIR="$(choose "test -d" "$HOME/workspace" "$HOME/des")"

export ZRC_FILE="$HOME/.zshrc"
export PAGER='less -F -X'
export GIT_PAGER='$PAGER'
export LS_COMMAND="$(choose is_executable exa lsd ls || echo false)"
export HEXDUMP_CMD="$(choose is_executable hexyl hd hexdump xxd || echo false)"

RC_FILE="$HOME/.profile"
if [ "$ZSH_VERSION" ]; then
	RC_FILE="$HOME/.zshrc"
elif [ "$BASH_VERSION" ]; then
	RC_FILE="$HOME/.bashrc"
fi
export RC_FILE

LOCAL_RC_FILE="${RC_FILE##*/}"
LOCAL_RC_FILE="$HOME/local.${LOCAL_RC_FILE#.}"
export LOCAL_RC_FILE


if is_executable delta; then
	export GIT_PAGER=delta
fi

if is_executable fd; then
	export FZF_DEFAULT_COMMAND='fd --type f'
fi

export OPENER=$(choose is_executable rifle xdg-open || echo false)
export TERMINAL=$(choose is_executable sensible-terminal alacritty gnome-terminal xterm || echo "${TERMINAL:-false}")
export EDITOR=$(choose is_executable nvim vim vi nano emacs || echo false)
export XEDITOR=$(choose is_executable gnvim gvim mousepad kate gedit || echo false)

# Configure coc to the global nodejs installation
if is_executable node; then
	COC_NODE_PATH="${COC_NODE_PATH:-$(cd ~ && "$(command -v asdf env | first_line)" which node)}"
	export COC_NODE_PATH
fi

