#! /usr/bin/env sh

# It's also a script in $DOTFILES_HOME/bin
# Mainly for compatiblity in envs without the bin on the path
_choose() (
	test_cmd="$1"
	shift

	for opt; do
		if eval " > /dev/null $test_cmd \"$opt\""; then
			echo "$opt"
			return
		fi
	done

	return 1
)

# It's also a script in $DOTFILES_HOME/bin
# Mainly for compatiblity in envs without the bin on the path
_is_executable() {
	type "$1" > /dev/null 2>&1
	return
}

export DOTFILES_HOME="${DOTFILES_HOME:-$HOME/dotfiles}"

export DOWNLOADS_DIR="$(_choose "test -d" "$HOME/Downloads" "$HOME/Transferências")"
export DOCUMENTS_DIR="$(_choose "test -d" "$HOME/Documents" "$HOME/Documentos")"
export WORKSPACE_DIR="$(_choose "test -d" "$HOME/workspace" "$HOME/des")"

export ZRC_FILE="$HOME/.zshrc"
export PAGER='less -F -X'
export GIT_PAGER='$PAGER'
export LS_COMMAND="$(_choose _is_executable exa lsd ls)"

if _is_executable delta; then
	export GIT_PAGER=delta
fi

if _is_executable fd; then
	export FZF_DEFAULT_COMMAND='fd --type f'
fi

export OPENER=$(_choose _is_executable rifle xdg-open)
export TERMINAL=$(_choose _is_executable alacritty gnome-terminal xterm)
export EDITOR=$(_choose _is_executable nvim vim vi nano emacs)
export XEDITOR=$(_choose _is_executable gnvim gvim mousepad kate gedit ||
	echo "$TERMINAL -e $EDITOR")

