[theme]
theme = "modern"

[icons]
icons = "awesome4"


[[block]]
block = "keyboard_layout"
interval = 2

[[block]]
block = "battery"
driver = "apc_ups"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used / $mem_total ($mem_used_percents.eng(w:2))"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
chip = "nct6798-isa-0290"

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4)"

[[block]]
block = "sound"

[[block]]
block = "temperature"
chip = "nvme-pci-0100"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime()"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 0.5
