#! /usr/bin/env sh

# Uses lsd if available on list aliases
LS_COMMAND=ls
if 2>&1 type lsd > /dev/null; then
  LS_COMMAND=lsd

  alias tree='lsd --tree'
fi

# Adding a alias to ghostscript, `gs` is used as a `git status` alias
if 2>&1 type -p gs > /dev/null; then
  alias gsc="$(which gs)"
fi

alias ll=$LS_COMMAND' -lah'
alias editor='$EDITOR'
alias reloadrc='source $RC_FILE'
alias rc='editor $RC_FILE'
alias lrc='editor $HOME/.local.zsh'
alias t7='tail -f -n 700'
alias npmr='npm run'
alias dotfiles='cd "$DOTFILES_HOME"'
alias o='xdg-open'
alias gs='git status'
alias r='ranger'
alias bc='bc -lq'

# Tmux is started by default, sometimes I need to get a session without it
# usually to open a new terminal emulator like allacrity or gnome-terminal and
# ssh something
alias notmux='env TMUX="" ZSH_TMUX_AUTOSTART=false'

# from https://datagrok.org/git/git-serve/
alias git_quickup='git daemon --verbose --export-all --base-path=.git --reuseaddr --strict-paths .git/'

# yep
alias :q='echo "u foooool"; sleep 1'
alias :wq='echo dumbass; sleep 1'

if 2>&1 type nvim > /dev/null; then
  alias vim='nvim'
fi

