#! /usr/bin/env zsh

# It's also a script in $DOTFILES_HOME/bin
# Mainly for compatiblity in envs without the bin on the path
choose() {
	test_cmd="$1"
	shift

	for a in "$@"; do
		if eval "> /dev/null $test_cmd \"$a\""; then
			echo "$a"
			return
		fi
	done

	_test=
	return 1
}

# It's also a script in $DOTFILES_HOME/bin
# Mainly for compatiblity in envs without the bin on the path
is_executable() {
	type "$1" > /dev/null 2>&1
	return
}

# Uses lsd if available on list aliases
LS_COMMAND="$(choose is_executable lsd exa ls)"

if ! [ "$LS_COMMAND" = ls ]; then
	alias tree="$LS_COMMAND --tree"
fi

# Adding a alias to ghostscript, `gs` is used as a `git status` alias
if 2>&1 type -p gs > /dev/null; then
  alias ghs="$(which gs)"
fi

# Overral a better hd
alias hd="$(choose is_executable hexyl hd hexdump xxd)"

# For sequencing cds, nice to aliases like 'des $PROJECT' or 'doc $DOC_DIR'
cds() {
	for arg in "$@"; do cd "$arg"; done
}

_cds() {
	local line=()

	for w in ${words[2,-1]}; do
		if ! [ -z "$w" ]; then
			local evaled="$(eval "echo $w")"
			line+=("$evaled")
		fi
	done

	local idx=$((CURRENT - 1))
	local opts=()

	local pref="${(j:/:)line[1,idx - 1]}"
	if ! [ -z "$pref" ]; then
		opts+=(-W "$(realpath "$pref")")
	fi

	if ! [ -z "${line[idx]}" ]; then
		opts+=(-g "${line[idx]}*")
	fi

	_path_files -/ "${opts[@]}"
}

if is_executable compdef; then
	compdef _cds cds
fi

alias ll="$LS_COMMAND -lah"
alias editor='$EDITOR'
alias reloadrc='source $RC_FILE'
alias rc='editor $RC_FILE'
alias lrc='editor $HOME/.local.zsh'
alias t7='tail -f -n 700'
alias npmr='npm run'
alias dotfiles='cd "${DOTFILES_HOME:-"$HOME"/dotfiles}"'
alias o="$OPENER"
alias gs='git status'
alias r='ranger'
alias bc='bc -lq'
alias tkothers='tmux list-sessions | awk -F: "!/attached/{print \$1}" | xargs -n1 tmux kill-session -t'
alias dfh='df -h'
alias please='sudo'
alias des='cds "$HOME/des"'
alias wrk='cds "${WORKSPACE_DIR:-"$HOME"/workspace}"'
alias dow='cds "${DOWNLOADS_DIR:-"$HOME"/Downloads}"'
alias doc='cds "${DOCUMENTS_DIR:-"$HOME"/Documents}"'

# Tmux is started by default, sometimes I need to get a session without it
# usually to open a new terminal emulator like allacrity or gnome-terminal and
# ssh something
alias notmux='env TMUX="" ZSH_TMUX_AUTOSTART=false'

# from https://datagrok.org/git/git-serve/
alias git_quickup='git daemon --verbose --export-all --base-path=.git --reuseaddr --strict-paths .git/'

# Help to quit bad habits, i can \vim anyways
if is_executable nvim; then
	alias vim='echo "You mean nvim?" && sleep 1 && :' # : is here to void arguments
fi

# yep
alias :q='echo "u foooool"; sleep 1'
alias :wq='echo dumbass; sleep 1'
