#! /usr/bin/env sh

_ag_exists() {
	type "$1" > /dev/null 2>&1
	return
}

_ag_choose_cmd() {
	while [ $# -gt 0 ]; do
		if _ag_exists "$1"; then
			echo "$1"
			return
		else
			shift
		fi
	done

	return 1
}

export DOTFILES_HOME="${DOTFILES_HOME:-$HOME/dotfiles}"
export RC_FILE="$HOME/.zshrc"
export GIT_PAGER='less -F -X'

if _ag_exists fd; then
	export FZF_DEFAULT_COMMAND='fd --type f'
fi

export OPENER=$(_ag_choose_cmd rifle xdg-open)
export TERMINAL=$(_ag_choose_cmd alacritty gnome-terminal xterm)
export EDITOR=$(_ag_choose_cmd nvim vim vi nano emacs)
export XEDITOR=$(_ag_choose_cmd gnvim gvim mousepad kate gedit ||
	echo "$TERMINAL -e $EDITOR")

