#! /usr/bin/env sh

# It's also a script in $DOTFILES_HOME/bin
# Mainly for compatiblity in envs without the bin on the path
choose() {
	test_cmd="$1"
	shift

	for a in "$@"; do
		if eval "> /dev/null $test_cmd \"$a\""; then
			echo "$a"
			return
		fi
	done

	test_cmd=''
	return 1
}

# It's also a script in $DOTFILES_HOME/bin
# Mainly for compatiblity in envs without the bin on the path
is_executable() {
	type "$1" > /dev/null 2>&1
	return
}

export DOWNLOADS_DIR="$(choose "test -d" "$HOME/Downloads" "$HOME/Transferências")"
export DOCUMENTS_DIR="$(choose "test -d" "$HOME/Documents" "$HOME/Documentos")"
export WORKSPACE_DIR="$(choose "test -d" "$HOME/workspace" "$HOME/des")"

export DOTFILES_HOME="${DOTFILES_HOME:-$HOME/dotfiles}"
export RC_FILE="$HOME/.zshrc"
export GIT_PAGER='less -F -X'

if is_executable delta; then
	export GIT_PAGER=delta
fi

if is_executable fd; then
	export FZF_DEFAULT_COMMAND='fd --type f'
fi

export OPENER=$(choose is_executable rifle xdg-open)
export TERMINAL=$(choose is_executable alacritty gnome-terminal xterm)
export EDITOR=$(choose is_executable nvim vim vi nano emacs)
export XEDITOR=$(choose is_executable gnvim gvim mousepad kate gedit ||
	echo "$TERMINAL -e $EDITOR")

